image: registry.gitlab.com/seltzer/kioku-srs/linux:latest
stages:
  - submodules
  - deps
  - build
  - docs

build_image:
  image: docker:git
  stage: build
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - echo "Building linux image"
    - cd $CI_PROJECT_DIR/docker/linux
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/linux .
    - docker push registry.gitlab.com/seltzer/kioku-srs/linux:latest
    - echo "Building mingw image"
    - cd $CI_PROJECT_DIR/docker/mingw
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/mingw .
    - docker push registry.gitlab.com/seltzer/kioku-srs/mingw:latest
    - echo "Building doxygen image"
    - cd $CI_PROJECT_DIR/docker/doxygen
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/doxygen .
    - docker push registry.gitlab.com/seltzer/kioku-srs/doxygen:latest
#   - docker run registry.gitlab.com/seltzer/kioku-srs/build /script/to/run/tests
# Don't build this unless we've got it on the docker branch - this is just to prevent it from building every time on master.
  only:
    - docker

submodules-deps:
  stage: submodules
  script:
    - git submodule update --init extern/libgit2
    - git submodule update --init extern/libssh2
  only:
    - master
  artifacts:
    paths:
      - extern/

submodules-build:
  stage: submodules
  script:
    - git submodule update --init extern/mongoose
    - git submodule update --init extern/greatest
    - git submodule update --init extern/generic-c-hashmap
    - git submodule update --init extern/utf8.h
    - git submodule update --init extern/parson
    - git submodule update --init extern/ims-json
    - git submodule update --init extern/tinydir
    - git submodule update --init extern/lua
  only:
    - master
  artifacts:
    paths:
      - extern/

deps-gcc:
  stage: deps
  dependencies:
    - submodules-deps
  script:
    - cd extern/libgit2
    - cmake . -G"Unix Makefiles" -DEMBED_SSH_PATH=$CI_PROJECT_DIR/extern/libssh2/ -DBUILD_CLAR=OFF
    - make
  only:
    - master
  artifacts:
    paths:
      - extern/

build-gcc:
  stage: build
  dependencies:
    - deps-gcc
    - submodules-build
  script:
    - mkdir $CI_JOB_NAME && cd $CI_JOB_NAME
    - cp $CI_PROJECT_DIR/extern/libgit2/*.so .
    - cmake .. -G"Unix Makefiles"
    - make
    - CTEST_OUTPUT_ON_FAILURE=1 make test
    # todo: Do both 64 & 32 bit builds
  only:
    - master
  artifacts:
    paths:
      - $CI_JOB_NAME/

deps-mingw32:
  stage: deps
  image: registry.gitlab.com/seltzer/kioku-srs/mingw:latest
  dependencies:
    - submodules-deps
  script:
    - cd extern/libgit2
    - cmake . -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$CI_PROJECT_DIR/cross/toolchain-mingw32.cmake -DEMBED_SSH_PATH=$CI_PROJECT_DIR/extern/libssh2/ -DBUILD_CLAR=OFF
    - make
  only:
    - master
  artifacts:
    paths:
      - extern/

deps-mingw64:
  stage: deps
  image: registry.gitlab.com/seltzer/kioku-srs/mingw:latest
  dependencies:
    - submodules-deps
  script:
    - cd extern/libgit2
    - cmake . -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$CI_PROJECT_DIR/cross/toolchain-mingw64.cmake -DEMBED_SSH_PATH=$CI_PROJECT_DIR/extern/libssh2/ -DBUILD_CLAR=OFF
    - make
  only:
    - master
  artifacts:
    paths:
      - extern/

build-mingw32:
  stage: build
  image: registry.gitlab.com/seltzer/kioku-srs/mingw:latest
  dependencies:
    - deps-mingw32
    - submodules-build
  script:
    - mkdir build && cd build
    - mv extern/libgit2/*.dll .
    - cmake .. -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$CI_PROJECT_DIR/cross/toolchain-mingw32.cmake 
    - make
  only:
    - master
  artifacts:
    paths:
      - build

build-mingw64:
  stage: build
  image: registry.gitlab.com/seltzer/kioku-srs/mingw:latest
  dependencies:
    - deps-mingw64
    - submodules-build
  script:
    - mkdir build && cd build
    - mv extern/libgit2/*.dll .
    - cmake .. -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=$CI_PROJECT_DIR/cross/toolchain-mingw64.cmake 
    - make
  only:
    - master
  artifacts:
    paths:
      - build


docs:
  stage: docs
  image: registry.gitlab.com/seltzer/kioku-srs/doxygen:latest
  script:
    - doxygen
  artifacts:
    paths:
      - doc
  only:
    - master
