image: registry.gitlab.com/seltzer/kioku-srs/build:latest
stages:
  - deps
  - build
  - docs

build_image:
  image: docker:git
  stage: build
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/build .
#   - docker run registry.gitlab.com/seltzer/kioku-srs/build /script/to/run/tests
    - docker push registry.gitlab.com/seltzer/kioku-srs/build:latest
# Don't build this unless we've got it on the docker branch - this is just to prevent it from building every time on master.
  only:
    - docker

deps:
  stage: deps
  script:
    - git submodule update --init extern/libgit2
    - git submodule update --init extern/libssh2
    - cd extern/libgit2
    - mkdir build && cd build
    - cmake .. -DEMBED_SSH_PATH=../../libssh2/ -DBUILD_CLAR=OFF
    - make
  only:
    - master
  artifacts:
    paths:
      - extern/libgit2/build

build:
  stage: build
  script:
    - git submodule update --init extern/mongoose
    - git submodule update --init extern/greatest
    - git submodule update --init extern/generic-c-hashmap
    - git submodule update --init extern/utf8.h
    - git submodule update --init extern/parson
    - git submodule update --init extern/ims-json
    - git submodule update --init extern/tinydir
    - git submodule update --init extern/lua
    - mkdir build
    - cp extern/libgit2/build/*.so build/
    - cd build
    - cmake ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=1 make test
  only:
    - master
  artifacts:
    paths:
      - build/

docs:
  stage: docs
  script:
    - doxygen
  artifacts:
    paths:
      - doc
  only:
    - master
