image: registry.gitlab.com/seltzer/kioku-srs/linux:latest
stages:
  - submodules
  - deps
  - build
  - docs

build_image:
  image: docker:git
  stage: build
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - echo "Building linux image"
    - cd $CI_PROJECT_DIR/docker/linux
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/linux .
    - docker push registry.gitlab.com/seltzer/kioku-srs/linux:latest
    - echo "Building doxygen image"
    - cd $CI_PROJECT_DIR/docker/doxygen
    - docker build -t registry.gitlab.com/seltzer/kioku-srs/doxygen .
    - docker push registry.gitlab.com/seltzer/kioku-srs/doxygen:latest
    # todo run tests
    # docker run registry.gitlab.com/seltzer/kioku-srs/build /script/to/run/tests
  # Don't build this unless we've got it on the docker branch - this is just to prevent it from building every time on master.
  only:
    - docker

submodules-deps:
  stage: submodules
  script:
    - git submodule update --init extern/libgit2
    - git submodule update --init extern/libssh2
  only:
    - master
  artifacts:
    paths:
      - extern/

submodules-build:
  stage: submodules
  script:
    - git submodule update --init extern/mongoose
    - git submodule update --init extern/greatest
    - git submodule update --init extern/generic-c-hashmap
    - git submodule update --init extern/utf8.h
    - git submodule update --init extern/parson
    - git submodule update --init extern/tinydir
    - git submodule update --init extern/lua
  only:
    - master
  artifacts:
    paths:
      - extern/

deps-gcc:
  stage: deps
  dependencies:
    - submodules-deps
  script:
    - ci/linux/build-deps.sh
  only:
    - master
  artifacts:
    paths:
      - extern/

build-gcc:
  stage: build
  dependencies:
    - deps-gcc
    - submodules-build
  script:
    - source ci/linux/build.sh
    # todo: Do both 64 & 32 bit builds
  only:
    - master
  artifacts:
    paths:
      - build

docs:
  stage: docs
  image: registry.gitlab.com/seltzer/kioku-srs/doxygen:latest
  script:
    - doxygen
  artifacts:
    paths:
      - doc
  only:
    - master
