language: c
os: osx
compiler:
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];then brew update; brew install libgcrypt; fi

script:
 - echo "Hello, Travis CI"
 - ci/osx/build-deps.sh
 - ci/osx/build.sh
