language: c
os: osx

machine:
  ruby:
    version: "2.3.1"

compiler:
  - gcc

dependencies:
  pre:
    - brew update
git:
  submodules: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];then brew update; brew install libgcrypt; fi
  - git submodule update --init

script:
 - echo "Hello, Travis CI"
 - ci/osx/build-deps.sh
 - ci/osx/build.sh
